name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/online-ticket-booking:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/online-ticket-booking:latest

      - name: Deploy to EC2 Server via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            if ! command -v docker &> /dev/null
            then
              echo "Docker not found. Installing..."
              sudo yum update -y
              sudo yum install docker -y
              sudo service docker start
              sudo usermod -aG docker $USER
            else
              echo "Docker is already installed."
              sudo service docker start
            fi

            echo "Deploying Docker container..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/online-ticket-booking:latest
            sudo docker stop online-ticket-booking || true
            sudo docker rm online-ticket-booking || true
            sudo docker run -d --name online-ticket-booking -p 3003:3003 ${{ secrets.DOCKER_USERNAME }}/online-ticket-booking:latest
