name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh -t ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          if [ ! -d "trainbooking" ]; then
            git clone https://github.com/719ABHI/Online_Ticket_Booking.git trainbooking
          fi
          cd trainbooking
          git pull origin main

          sudo docker stop trainbooking-container || true
          sudo docker rm trainbooking-container || true
          sudo docker build -t trainbooking-app .
          sudo docker run -d -p 3003:3003 --name trainbooking-container trainbooking-app
        EOF
